[ClassVersion("1.0.0.0"), FriendlyName("CredentialValidation")]
class CredentialValidation : OMI_BaseResource
{
    [Key] string Name;
    [Required, Description("Test Credentials for Script Base"), EmbeddedInstance("MSFT_Credential")] String Credential;
};