# rustfmt.toml for DSC
# Note that some of these are only available in the nightly channel of rustfmt.

# Basic layout
max_width = 120
hard_tabs = false
tab_spaces = 4

# Imports
reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Comments & docs
wrap_comments = true
format_code_in_doc_comments = true
normalize_doc_attributes = true

# Macro bodies, etc.
format_macro_bodies = false

# Edition (for parsing behavior)
edition = "2021"

# Error handling
error_on_line_overflow = true
error_on_unformatted = true
overflow_delimited_expr = false
