// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use super::macros::*;

use crate::schemas::dsc_repo::DscRepoSchema;

define_container_field!{
    base_name: "tracing",
    folder_path: "settings/fields",
    field_definition: {
        /// Defines the available settings for the tracing configuration in DSC.
        ///
        /// This struct is used to represent the settings as they are defined
        /// in both [`PolicyFileData`] and [`PreferenceFileData`].
        ///
        /// DSC emits messages to `stderr` to provide information about the
        /// execution lifecycle. Every message is emitted with a different
        /// severity level. DSC supports emitting trace messages in multiple
        /// formats.
        ///
        /// # Trace level
        ///
        /// By default, DSC emits only [`Warn`] and [`Error`] messages to
        /// stderr.
        ///
        /// Users can define what level of messages to emit by:
        ///
        /// 1. Defining the `tracing.level` field in the [`Policy`],
        ///    [`Machine`], [`User`], or [`Workspace`] settings files.
        /// 1. Defining the [`DSC_TRACE_LEVEL`] environment variable.
        /// 1. Specifying the [`--trace-level`] global command line argument.
        ///
        /// When the trace level is set, DSC will emit messages of the
        /// specified severity and higher to stderr. For example, if the trace
        /// level is set to [`Info`], DSC will emit messages with [`Info`],
        /// [`Warn`], and [`Error`] severity levels. DSC won't emit messages
        /// with [`Debug`] or [`Trace`] severity levels.
        ///
        /// # Trace format
        ///
        /// By default, DSC emits messages to stderr as colorized human-readable
        /// text.
        ///
        /// Users can override the default trace format by:
        ///
        /// 1. Defining the `tracing.format` field in the [`Policy`],
        ///    [`Machine`], [`User`], or [`Workspace`] settings files.
        /// 1. Defining the [`DSC_TRACE_FORMAT`] environment variable.
        /// 1. Specifying the [`--trace-format`] global command line argument.
        ///
        /// The available trace formats include:
        ///
        /// - [`Default`]: DSC emits messages to stderr in the default colorized
        ///   human-readable text format.
        /// - [`Plaintext`]: DSC emits messages to stderr as human readable text
        ///   without colorization.
        /// - [`Json`]: DSC emits messages to stderr as compressed JSON objects.
        ///
        /// [`PolicyFileData`]: crate::settings::sources::PolicyFileData
        /// [`PreferenceFileData`]: crate::settings::sources::PreferenceFileData
        /// [`Error`]: TracingLevelField::Error
        /// [`Warn`]: TracingLevelField::Warn
        /// [`Info`]: TracingLevelField::Info
        /// [`Debug`]: TracingLevelField::Debug
        /// [`Trace`]: TracingLevelField::Trace
        /// [`Policy`]: crate::settings::DscSettingsScope::Policy
        /// [`Machine`]: crate::settings::DscSettingsScope::Machine
        /// [`User`]: crate::settings::DscSettingsScope::User
        /// [`Workspace`]: crate::settings::DscSettingsScope::Workspace
        /// [`Default`]: TracingFormatField::Default
        /// [`Plaintext`]: TracingFormatField::Plaintext
        /// [`Json`]: TracingFormatField::Json
        /// [`DSC_TRACE_LEVEL`]: crate::settings::sources::EnvironmentData::dsc_trace_level
        /// [`DSC_TRACE_FORMAT`]: crate::settings::sources::EnvironmentData::dsc_trace_format
        /// [`--trace-level`]: crate::settings::sources::CommandLineData::trace_level
        /// [`--trace-format`]: crate::settings::sources::CommandLineData::trace_format
        #[schemars(extend("unevaluatedProperties" = false))]
        struct TracingFileData {
            /// Specifies the trace level to use for logging and diagnostics.
            ///
            /// This field controls the verbosity of the logs generated by DSC.
            /// Messages with a lower level than the specified trace level will
            /// be filtered out and not emitted.
            ///
            /// The available trace levels, in order of increasing verbosity,
            /// are:
            ///
            /// - `error`
            /// - `warn`
            /// - `info`
            /// - `debug`
            /// - `trace`
            level: TracingLevelField = TracingLevelField::Warn,
            /// Specifies the trace format to use for logging and diagnostics.
            ///
            /// This field controls the text that DSC emits to stderr for trace
            /// messages.
            ///
            /// The available trace formats are:
            ///
            /// - `default` - Colorized human-readable text with timestamps and
            ///   log levels.
            /// - `plaintext` - Human-readable text without colorization.
            /// - `json` - Structured output as compressed JSON objects
            ///   suitable for machine parsing.
            format: TracingFormatField = TracingFormatField::Default,
        }
    },
    resolved_container_type: {
        /// Defines the resolved settings for tracing in DSC.
        ///
        /// For more information about the available settings, see
        /// [`TracingFileData`].
        TracingResolvedSettings
    },
    code_default_type: {
        /// Defines the structure of the code defaults for the tracing settings
        /// in DSC.
        ///
        /// For more information about the available settings, see
        /// [`TracingFileData`]. For more information about the defaults, see
        /// [`CODE_DEFAULT_TRACING`].
        TracingCodeDefaults
    },
    code_default_const: {
        /// Defines the default values for the tracing configuration in DSC.
        ///
        /// The following snippet shows the effective code defaults as YAML
        /// data:
        ///
        /// ```yaml
        /// tracing:
        ///   level: warn
        ///   format: default
        /// ```
        ///
        /// With these defaults, DSC will emit warnings and higher-severity
        /// messages in the default trace format, which emits human-readable
        /// text to `stderr` with colorization and timestamps.
        ///
        /// For more information about defining the settings, see
        /// [`TracingFileData`].
        CODE_DEFAULT_TRACING
    }
}

define_string_enum_field!{
    base_name: "level",
    folder_path: "settings/fields/tracing",
    parse_error_variant: InvalidTracingLevel,
    field_definition: {
        /// Represents the levels of trace messages that DSC can emit.
        ///
        /// The levels are ordered from least to most verbose:
        ///
        /// 1. [`Error`]
        /// 1. [`Warn`]
        /// 1. [`Info`]
        /// 1. [`Debug`]
        /// 1. [`Trace`]
        ///
        /// When emitting trace messages to stderr, DSC filters messages based
        /// on the configured trace level. DSC only emits messages at or above
        /// the configured level. For example, if the trace level is set to
        /// [`Warn`], DSC will emit warning and error messages, but not
        /// informational, debug, or trace messages.
        ///
        /// [`Error`]: Self::Error
        /// [`Warn`]: Self::Warn
        /// [`Info`]: Self::Info
        /// [`Debug`]: Self::Debug
        /// [`Trace`]: Self::Trace
        enum TracingLevelField {
            /// Indicates that DSC should only emit error messages.
            Error { display: "error", lowercase: "error" },
            /// Indicates that DSC should emit warning and error messages.
            Warn { display: "warn", lowercase: "warn" },
            /// Indicates that DSC should emit informational, warning, and
            /// error messages.
            Info { display: "info", lowercase: "info" },
            /// Indicates that DSC should emit debug, informational, warning,
            /// and error messages.
            Debug { display: "debug", lowercase: "debug" },
            /// Indicates that DSC should emit all messages, including trace
            /// messages.
            Trace { display: "trace", lowercase: "trace" },
        }
    }
}

impl From<TracingLevelField> for tracing::Level {
    fn from(level: TracingLevelField) -> Self {
        match level {
            TracingLevelField::Error => tracing::Level::ERROR,
            TracingLevelField::Warn => tracing::Level::WARN,
            TracingLevelField::Info => tracing::Level::INFO,
            TracingLevelField::Debug => tracing::Level::DEBUG,
            TracingLevelField::Trace => tracing::Level::TRACE,
        }
    }
}

impl From<tracing::Level> for TracingLevelField {
    fn from(level: tracing::Level) -> Self {
        match level {
            tracing::Level::ERROR => TracingLevelField::Error,
            tracing::Level::WARN => TracingLevelField::Warn,
            tracing::Level::INFO => TracingLevelField::Info,
            tracing::Level::DEBUG => TracingLevelField::Debug,
            tracing::Level::TRACE => TracingLevelField::Trace,
        }
    }
}

define_string_enum_field!{
    base_name: "format",
    folder_path: "settings/fields/tracing",
    parse_error_variant: InvalidTracingFormat,
    field_definition: {
        /// Indicates how DSC should format trace messages when emitting them
        /// to `stderr`.
        ///
        /// The available trace formats are:
        ///
        /// - [`Default`] - Colorized human-readable text with timestamps and
        ///   log levels.
        /// - [`Plaintext`] - Human-readable text without colorization.
        /// - [`Json`] - Structured output as compressed JSON objects suitable
        ///   for machine parsing.
        ///
        /// [`Default`]: Self::Default
        /// [`Plaintext`]: Self::Plaintext
        /// [`Json`]: Self::Json
        enum TracingFormatField {
            /// Indicates that DSC should emit trace messages to `stderr` in
            /// the default human-readable format.
            Default { display: "default", lowercase: "default" },
            /// Indicates that DSC should emit trace messages to `stderr` in a
            /// plain text format.
            Plaintext { display: "plaintext", lowercase: "plaintext" },
            /// Indicates that DSC should emit trace messages to `stderr` in a
            /// structured JSON format.
            Json { display: "json", lowercase: "json" },
        }
    }
}
