// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use std::fmt::{Display, Formatter};
use std::hash::Hash;
use std::str::FromStr;
use std::sync::OnceLock;

use miette::Diagnostic;
use regex::{Regex, RegexBuilder};
use rust_i18n::t;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::types::{FullyQualifiedTypeName, FullyQualifiedTypeNameError};
use crate::util::convert_wildcard_to_regex;

/// Defines the wildcard type name for filtering DSC resources or extensions by name.
/// 
/// The wildcard type name is used to match against [`FullyQualifiedTypeName`]s in order to filter
/// for specific resources or extensions based on their type names, while allowing for flexible
/// patterns using wildcard characters (`*`).
/// 
/// The wildcard type name supports the same overall structure as a fully qualified type name
/// (owner, optional namespaces, and name) but allows for the presence of wildcard characters in any
/// segment. The presence of wildcard characters means that the validation rules for fully qualified
/// type names are relaxed to allow for wildcard characters.
/// 
/// The default value for a wildcard type name is `*`, which matches any fully qualified type name.
/// This provides a convenient default for cases where the user wants to match all type names
/// without needing to specify a wildcard pattern.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct WildcardTypeName {
    /// The original input text for the wildcard type name, which must contain at least one
    /// wildcard character (`*`).
    text: String,
    /// The compiled regex pattern that corresponds to the wildcard type name, used for matching
    /// candidate fully qualified type names against the wildcard pattern.
    /// 
    /// This regex is generated by converting the wildcard type name into a regex pattern, where
    /// the wildcard characters are replaced with `.*` to match any sequence of characters, and
    /// other characters are escaped as needed to ensure they are treated as literals in the regex
    /// pattern.
    /// 
    /// The regex is compiled during the parsing/validation of the wildcard type name, and if the
    /// resulting regex pattern is invalid, an error is returned. This allows for early detection
    /// of invalid wildcard patterns that would not be usable for matching
    /// [`FullyQualifiedTypeName`]s.
    regex: Regex,
}

/// Defines the various errors that can occur when parsing and working with instances of
/// [`WildcardTypeName`].
#[derive(Debug, Clone, PartialEq, Error, Diagnostic)]
pub enum WildcardTypeNameError {
    /// Indicates that the provided wildcard type name is invalid because it doesn't contain any
    /// wildcard characters.
    #[error("{t}", t = t!(
        "types.wildcard_type_name.noWildcard",
        "text" => text
    ))]
    NoWildcard {
        /// The input text that failed to parse as a wildcard type name.
        text: String,
    },

    /// Indicates that the provided wildcard type name is an empty string.
    #[error("{t}", t = t!(
        "types.wildcard_type_name.emptyTypeName"
    ))]
    EmptyTypeName,

    /// Indicates that the provided wildcard type name is invalid for one or more reasons.
    /// 
    /// This error can occur for multiple reasons, such as invalid characters in the owner,
    /// namespace, or name segments, or invalid regex patterns resulting from the wildcard
    /// characters. The `errors` field contains a list of specific validation errors that were
    /// encountered while parsing the wildcard type name, to enable reviewing all issues rather
    /// than just the first one encountered.
    #[error("{t}", t = t!(
        "types.wildcard_type_name.invalidTypeName",
        "text" => text,
        "err" => errors.iter().map(|e| e.to_string()).collect::<Vec<String>>().join(", ")
    ))]
    InvalidTypeName {
        /// The input text that failed to parse as a wildcard type name.
        text: String,
        /// A list of specific validation errors that were encountered while parsing the wildcard
        /// type name.
        /// 
        /// Each error in this list indicates a specific issue with the input text, such as invalid
        /// characters in a segment or an invalid regex pattern.
        #[related]
        errors: Vec<WildcardTypeNameError>,
    },

    /// Indicates that the provided wildcard type name is invalid because it contains invalid
    /// characters in the owner segment (the first segment before any dots or slashes).
    /// 
    /// The owner segment must contain only unicode alphanumeric characters, underscores, or
    /// wildcard characters (`*`). If it contains any other characters, validation raises this
    /// error in the `errors` field of the main [`InvalidTypeName`] error.
    /// 
    /// [`InvalidTypeName`]: Self::InvalidTypeName
    #[error("{t}", t = t!(
        "types.wildcard_type_name.invalidOwnerSegment",
        "owner" => segment_text
    ))]
    InvalidOwnerSegment {
        /// The owner segment text that contains invalid characters.
        segment_text: String,
    },

    /// Indicates that the provided wildcard type name is invalid because it defines a namespace
    /// segment without defining a non-dot character before it, like `.Contoso.Example/Resource`.
    /// 
    /// The owner segment must be defined before any namespace segments. It must contain only
    /// unicode alphanumeric characters, underscores, and wildcard characters (`*`). If the input
    /// string contains a namespace segment that is not preceded by a valid owner segment,
    /// validation raises this error in the `errors` field of the main [`InvalidTypeName`] error.
    /// 
    /// [`InvalidTypeName`]: Self::InvalidTypeName
    #[error("{t}", t = t!(
        "types.wildcard_type_name.emptyOwnerSegment"
    ))]
    EmptyOwnerSegment,

    /// Indicates that the provided wildcard type name is invalid because it contains invalid
    /// characters in a namespace segment (any segments between the owner and the name, separated by
    /// dots (`.`)).
    /// 
    /// Each namespace segment must contain only unicode alphanumeric characters, underscores, or
    /// wildcard characters (`*`). If it contains any other characters, validation raises this
    /// error in the `errors` field of the main [`InvalidTypeName`] error.
    /// 
    /// [`InvalidTypeName`]: Self::InvalidTypeName
    #[error("{t}", t = t!(
        "types.wildcard_type_name.invalidNamespaceSegment",
        "namespace" => segment_text
    ))]
    InvalidNamespaceSegment {
        /// The namespace segment text that contains invalid characters.
        segment_text: String,
    },

    /// Indicates that the provided wildcard type name is invalid because it contains
    /// an empty namespace segment (i.e., two consecutive dots with no characters in between).
    /// 
    /// If the wildcard type name contains any empty namespace segments, validation raises
    /// this error in the `errors` field of the main [`InvalidTypeName`] error.
    /// 
    /// [`InvalidTypeName`]: Self::InvalidTypeName
    #[error("{t}", t = t!(
        "types.wildcard_type_name.emptyNamespaceSegment",
        "index" => index
    ))]
    EmptyNamespaceSegment {
        /// The 1-based index of the empty namespace segment in the wildcard type name.
        index: usize,
    },

    /// Indicates that the provided wildcard type name is invalid because it contains invalid
    /// characters in the name segment (the last segment, which follows a forward slash (`/`)).
    /// 
    /// The name segment must contain only unicode alphanumeric characters, underscores, or wildcard
    /// characters (`*`). If it contains any other characters, validation raises this error in the
    /// `errors` field of the main [`InvalidTypeName`] error.
    /// 
    /// [`InvalidTypeName`]: Self::InvalidTypeName
    #[error("{t}", t = t!(
        "types.wildcard_type_name.invalidNameSegment",
        "name" => segment_text
    ))]
    InvalidNameSegment {
        /// The name segment text that contains invalid characters.
        segment_text: String,
    },

    /// Indicates that the provided wildcard type name is invalid because it is missing the
    /// required name segment (i.e., the segment after the forward slash (`/`)).
    ///
    /// A fully qualified type name must include a name segment. For a wildcard type name, the
    /// name segment can only be empty when a prior segment contains a wildcard that can match the
    /// name segment.
    /// 
    /// For example, `Contoso.*.Example` would not be valid because the literal
    /// namespace segment after the wildcard can never match a [`FullyQualifiedTypeName`] where
    /// the last namespace is always followed by a slash and the name segment.
    /// 
    /// The input strings `Contoso*` and `Contoso.Example*` are valid because there are no literal
    /// matches after the wildcards that would prevent matching a name segment.
    /// 
    /// If the input string is defined in a way that can't match a valid [`FullyQualifiedTypeName`]
    /// because of a missing name segment, validation raises this error in the `errors` field of
    /// the main [`InvalidTypeName`] error.
    ///
    /// [`InvalidTypeName`]: Self::InvalidTypeName
    #[error("{t}", t = t!(
        "types.wildcard_type_name.missingNameSegment"
    ))]
    MissingNameSegment,

    /// Indicates that the provided wildcard type name is invalid because it could not be converted
    /// into a valid regex pattern, which is necessary for matching candidate
    /// [`FullyQualifiedTypeName`]s against the wildcard pattern.
    /// 
    /// This can occur if the wildcard characters are used in a way that results in an invalid
    /// regex pattern when converted, such as defining consecutive wildcard characters without
    /// proper escaping.
    #[error("{t}", t = t!(
        "types.wildcard_type_name.invalidRegex",
        "name" => text,
        "err" => err
    ))]
    InvalidRegex {
        /// The input text that failed to parse as a wildcard type name.
        text: String,
        /// The specific regex error that was encountered when attempting to convert the wildcard
        /// type name into a regex pattern for matching.
        /// 
        /// This error provides details about why the regex pattern was invalid, which can help
        /// with diagnosing issues in the wildcard type name format.
        #[source]
        err: regex::Error,
    },
    #[error("{t}", t = t!(
        "types.wildcard_type_name.invalidErrorConversion",
        "err" => err
    ))]
    InvalidErrorConversion {
        /// The specific error that was encountered when attempting to convert the wildcard type
        /// name into a regex pattern for matching, but which is not a regex::Error and thus
        /// can't be included in the `InvalidRegex` error variant.
        err: FullyQualifiedTypeNameError,
    }
}

/// This static lazily defines the validating regex for [`WildcardTypeName`]. It enables the
/// [`Regex`] instance to be constructed once, the first time it's used, and then reused on all
/// subsequent validation calls. It's kept private, since the API usage is to invoke the
/// [`WildcardTypeName::parse()`] method for direct validation or to leverage this static from
/// within the constructor for [`WildcardTypeName`].
static VALIDATING_SEGMENT_REGEX: OnceLock<Regex> = OnceLock::new();

impl WildcardTypeName {
    /// Parses a string into a [`WildcardTypeName`] instance.
    /// 
    /// # Arguments
    /// 
    /// - `text` - The input string to parse as a wildcard type name.
    /// 
    /// # Errors
    /// 
    /// This function returns a [`WildcardTypeNameError`] if the input string is not a valid
    /// wildcard type name. The error will indicate which validation rules were violated and
    /// include diagnostics for every validation error encountered during parsing.
    /// 
    /// # Returns
    /// 
    /// A result containing the parsed [`WildcardTypeName`] or an error if the input is invalid.
    /// 
    /// # Examples
    /// 
    /// The following snippets show how various valid input strings are parsed:
    /// 
    /// - Single wildcard character, matching any type name:
    /// 
    ///   ```rust
    ///   # use dsc_lib::types::WildcardTypeName;
    ///   let _ = WildcardTypeName::parse("*").unwrap();
    ///   ```
    /// 
    /// - Wildcard character in the name segment, matching any type name with the specified owner
    ///   and namespaces:
    /// 
    ///   ```rust
    ///   # use dsc_lib::types::WildcardTypeName;
    ///   let _ = WildcardTypeName::parse("Contoso.Example/*").unwrap();
    ///   ```
    /// 
    /// - Wildcard character in the namespace segment, matching any type name with the specified
    ///   owner and first namespace:
    /// 
    ///   ```rust
    ///   # use dsc_lib::types::WildcardTypeName;
    ///   let _ = WildcardTypeName::parse("Contoso.Example.*").unwrap();
    ///   ```
    /// 
    /// The following snippets show examples of invalid input strings and the corresponding errors:
    /// 
    /// - An empty input string:
    /// 
    ///   ```rust
    ///   # use dsc_lib::types::{WildcardTypeName, WildcardTypeNameError};
    ///   # use pretty_assertions::assert_eq;
    ///   assert_eq!(
    ///       WildcardTypeName::parse("").unwrap_err(),
    ///       WildcardTypeNameError::EmptyTypeName
    ///   );
    ///   ```
    /// 
    /// - A string without any wildcard characters:
    /// 
    ///   ```rust
    ///   # use dsc_lib::types::{WildcardTypeName, WildcardTypeNameError};
    ///   # use pretty_assertions::assert_eq;
    ///   assert_eq!(
    ///       WildcardTypeName::parse("Contoso.Example/Resource").unwrap_err(),
    ///       WildcardTypeNameError::NoWildcard {
    ///           text: "Contoso.Example/Resource".to_string()
    ///       }
    ///   );
    ///   ```
    /// 
    /// - An empty owner segment before the first namespace:
    /// 
    ///   ```rust
    ///   # use dsc_lib::types::{WildcardTypeName, WildcardTypeNameError};
    ///   # use pretty_assertions::assert_eq;
    ///   assert_eq!(
    ///       WildcardTypeName::parse(".Example/Resource*").unwrap_err(),
    ///       WildcardTypeNameError::InvalidTypeName {
    ///           text: ".Example/Resource*".to_string(),
    ///           errors: vec![
    ///               WildcardTypeNameError::EmptyOwnerSegment
    ///           ],
    ///       }
    ///   );
    ///   ```
    ///
    /// - An empty owner segment before the slash:
    /// 
    ///   ```rust
    ///   # use dsc_lib::types::{WildcardTypeName, WildcardTypeNameError};
    ///   # use pretty_assertions::assert_eq;
    ///   assert_eq!(
    ///       WildcardTypeName::parse("/Resource*").unwrap_err(),
    ///       WildcardTypeNameError::InvalidTypeName {
    ///           text: "/Resource*".to_string(),
    ///           errors: vec![
    ///               WildcardTypeNameError::EmptyOwnerSegment
    ///           ],
    ///       }
    ///   );
    ///   ```
    /// 
    /// - An empty namespace segment:
    /// 
    ///   ```rust
    ///   # use dsc_lib::types::{WildcardTypeName, WildcardTypeNameError};
    ///   # use pretty_assertions::assert_eq;
    ///   assert_eq!(
    ///       WildcardTypeName::parse("Contoso..Example/Resource*").unwrap_err(),
    ///       WildcardTypeNameError::InvalidTypeName {
    ///           text: "Contoso..Example/Resource*".to_string(),
    ///           errors: vec![
    ///               WildcardTypeNameError::EmptyNamespaceSegment {
    ///                   index: 1
    ///               }
    ///           ],
    ///       }
    ///   );
    ///   ```
    /// 
    /// - Missing name segment when required because no prior wildcard can match the name segment:
    /// 
    ///   ```rust
    ///   # use dsc_lib::types::{WildcardTypeName, WildcardTypeNameError};
    ///   # use pretty_assertions::assert_eq;
    ///   assert_eq!(
    ///       WildcardTypeName::parse("Contoso.*.Example/").unwrap_err(),
    ///       WildcardTypeNameError::InvalidTypeName {
    ///           text: "Contoso.*.Example/".to_string(),
    ///           errors: vec![
    ///               WildcardTypeNameError::MissingNameSegment
    ///           ],
    ///       }
    ///   );
    ///   ```
    /// 
    /// - Invalid characters in the any segment:
    /// 
    ///   ```rust
    ///   # use dsc_lib::types::{WildcardTypeName, WildcardTypeNameError};
    ///   # use pretty_assertions::assert_eq;
    ///   assert_eq!(
    ///       WildcardTypeName::parse("Conto$o.Ex@mple/Re$ource*").unwrap_err(),
    ///       WildcardTypeNameError::InvalidTypeName {
    ///           text: "Conto$o.Ex@mple/Re$ource*".to_string(),
    ///           errors: vec![
    ///               WildcardTypeNameError::InvalidOwnerSegment {
    ///                   segment_text: "Conto$o".to_string(),
    ///               },
    ///               WildcardTypeNameError::InvalidNamespaceSegment {
    ///                   segment_text: "Ex@mple".to_string(),
    ///               },
    ///               WildcardTypeNameError::InvalidNameSegment {
    ///                   segment_text: "Re$ource*".to_string(),
    ///               },
    ///           ],
    ///       }
    ///   );
    ///   ```
    pub fn parse(text: &str) -> Result<Self, WildcardTypeNameError> {
        // If the text is empty, it's not a valid wildcard type name. Fail fast in this case to
        // avoid unnecessary processing and provide a clearer error message.
        if text.is_empty() {
            return Err(WildcardTypeNameError::EmptyTypeName);
        }

        // If the text doesn't contain any wildcard characters, it's not a valid wildcard type name,
        // even if it would otherwise match the fully qualified type name pattern. Fail fast in
        // this case to avoid unnecessary regex validation and to provide a clearer error message
        // about the specific issue.
        if !text.contains('*') {
            return Err(WildcardTypeNameError::NoWildcard {
                text: text.to_string(),
            });
        }

        let errors = &mut Vec::<WildcardTypeNameError>::new();
        let (owner, namespaces, name) = Self::parse_segments(
            text,
            errors
        );

        // The name segment is required if no wildcard is defined that can match the name
        // segment. For example, `Contoso.*.Example` would require a name segment because it
        // defines a wildcard in a prior namespace segment with a following literal namespace
        // segment.
        let require_name = if namespaces.is_empty() {
            !owner.contains('*')
        } else {
            !namespaces.last().unwrap().contains('*')
        };
        if name.is_empty() && require_name {
            errors.push(WildcardTypeNameError::MissingNameSegment);
        }

        // Validate the name segment for invalid characters if it's defined.
        let validating_segment_regex = Self::init_validating_segment_regex();
        if !name.is_empty() && !validating_segment_regex.is_match(&name) {
            errors.push(WildcardTypeNameError::InvalidNameSegment {
                segment_text: name.clone(),
            });
        }

        // Construct the regular expression.
        let pattern = convert_wildcard_to_regex(text);
        let regex = match RegexBuilder::new(&pattern).case_insensitive(true).build() {
            Ok(r) => r,
            Err(err) => {
                errors.push(WildcardTypeNameError::InvalidRegex {
                    text: text.to_string(),
                    err
                });

                // Placeholder regex since we have to return something, but this value won't be
                // used since we'll return an error due to the invalid regex pattern. WIthout this
                // placeholder, the function would fail to compile since the `regex` variable would
                // be potentially uninitialized in the error case and we can't tell the compiler to
                // ignore that even though the code logic guarantees it won't be used.
                Regex::new("").unwrap() 
            }
        };

        // Return result and ensure all failures are bubbled up in the error case.
        if errors.is_empty() {
            Ok(Self { text: text.to_string(), regex })
        } else {
            return Err(WildcardTypeNameError::InvalidTypeName {
                text: text.to_string(),
                errors: errors.clone(),
            });
        }
    }

    /// Private helper to parse the input into segments and collect validation errors for owner
    /// and namespace segments.
    /// 
    /// This is used by the public `parse()` method to perform the initial parsing of the input
    /// string into its constituent segments. It reuses the implementation from
    /// [`FullyQualifiedTypeName::parse_segments()`], but converts the errors into the appropriate
    /// [`WildcardTypeNameError`] variants and collects them in the provided `errors` vector for
    /// bubbling up in the main error handling logic of the `parse()` method.
    /// 
    /// # Arguments
    /// 
    /// - `text` - The input string to parse into segments.
    /// - `errors`: A mutable reference to a vector for collecting any validation errors encountered
    ///   while parsing the segments. This allows the method to accumulate multiple errors for
    ///   different segments of the type name.
    /// 
    /// # Returns
    /// 
    /// The method returns the parsed segments (`owner`, `namespaces`, and `name`) as a tuple. Any
    /// validation errors encountered during parsing are added to the provided `errors` vector for
    /// the caller to handle.
    pub(crate) fn parse_segments(text: &str, errors: &mut Vec<WildcardTypeNameError>) -> (String, Vec<String>, String) {
        // Reuse the segment parsing logic from FullyQualifiedTypeName since the overall structure
        // is the same, but we need to provide a different validating regex that allows for
        // wildcard characters and the name segment may be optional depending on the presence of
        // wildcards in prior segments.
        let fqtn_errors = &mut Vec::<FullyQualifiedTypeNameError>::new();
        let validating_segment_regex = Self::init_validating_segment_regex();
        let parsed = FullyQualifiedTypeName::parse_segments(
            text,
            validating_segment_regex,
            fqtn_errors
        );
        // Convert the FQTN errors and add into the WCTN error collection
        errors.extend(fqtn_errors.into_iter().map(|e| {
            match TryInto::<WildcardTypeNameError>::try_into(e.clone()) {
                Ok(wtne) => wtne,
                Err(e) => e,
            }
        }));
        // Return the parsed segments.
        parsed
    }
    /// Returns `true` if the wildcard type name has a length of zero and otherwise `false`.
    pub fn is_empty(&self) -> bool {
        self.text.is_empty()
    }

    /// Determines if a given candidate [`FullyQualifiedTypeName`] matches the wildcard pattern
    /// defined by this [`WildcardTypeName`].
    /// 
    /// This method uses the compiled regex pattern corresponding to the wildcard type name to
    /// check if the candidate fully qualified type name matches the wildcard pattern.
    /// 
    /// # Arguments
    /// 
    /// - `candidate` - The [`FullyQualifiedTypeName`] to check.
    /// 
    /// # Returns
    /// 
    /// `true` if the candidate fully qualified type name matches the wildcard pattern, and `false`
    /// otherwise.
    /// 
    /// # Examples
    /// 
    /// The following snippet shows how a wildcard type name can be used to match candidate
    /// fully qualified type names:
    /// 
    /// ```rust
    /// # use dsc_lib::types::{WildcardTypeName, FullyQualifiedTypeName};
    /// let wildcard = WildcardTypeName::parse("Contoso.*.Example/*").unwrap();
    /// assert!(wildcard.is_match(
    ///     &FullyQualifiedTypeName::parse("Contoso.A.Example/Resource").unwrap()
    /// ));
    /// assert!(wildcard.is_match(
    ///     &FullyQualifiedTypeName::parse("Contoso.B.Example/AnotherResource").unwrap()
    /// ));
    /// assert!(!wildcard.is_match(
    ///     &FullyQualifiedTypeName::parse("Contoso.Example/Resource").unwrap())
    /// ); 
    /// ```
    pub fn is_match(&self, candidate: &FullyQualifiedTypeName) -> bool {
        self.regex.is_match(candidate.as_ref())
    }

    /// Returns a reference to the compiled regex pattern that corresponds to this wildcard type
    /// name.
    /// 
    /// The regular expression replaces the wildcard characters (`*`) in the original text with
    /// the subexpression `.*?` to enable matching any sequence of characters in place of the
    /// wildcard. Any other special regex characters in the original text are escaped to ensure
    /// they are treated as literals in the regex pattern. The resulting regex pattern is anchored
    /// to match the entire input string.
    /// 
    /// # Returns
    /// 
    /// A reference to the compiled regex pattern.
    /// 
    /// # Examples
    /// 
    /// The following snippet shows the regular expression for a [`WildcardTypeName`] defined as
    /// a single wildcard character, which should match any fully qualified type name:
    /// 
    /// ```rust
    /// # use dsc_lib::types::WildcardTypeName;
    /// # use pretty_assertions::assert_eq;
    /// assert_eq!(
    ///     WildcardTypeName::parse("*").unwrap().as_regex().as_str(),
    ///     r"^.*?$"
    /// );
    /// ```
    /// 
    /// The following snippet shows the regular expression for a [`WildcardTypeName`] defined as
    /// `Contoso.*.Example/*`:
    /// 
    /// ```rust
    /// # use dsc_lib::types::WildcardTypeName;
    /// # use pretty_assertions::assert_eq;
    /// assert_eq!(
    ///    WildcardTypeName::parse("Contoso.*.Example/*").unwrap().as_regex().as_str(),
    ///   r"^Contoso\..*?\.Example/.*?$"
    /// );
    /// 
    pub fn as_regex(&self) -> &Regex {
        &self.regex
    }

    /// Defines the regular expression for validating a segment in a wildcard type name.
    /// 
    /// Each segment must contain only alphanumeric characters, underscores, or wildcard characters
    /// (`*`). This regular expression is applied to each individual segment of the type name
    /// (owner, namespaces, and name) rather than the entire type name string, since the presence
    /// of wildcard characters means that the overall structure of the type name cannot be strictly
    /// validated with a single regex pattern.
    /// 
    /// This also obviates needing to check for the namespace separator (`.`) and type/name
    /// separator (`/`) in the regex pattern, since the segments are validated individually after
    /// slicing the input string based on those separators.
    pub const VALIDATING_SEGMENT_PATTERN: &'static str = r"^(?:\w|\*)+$";

    /// Initializes and returns the validating regex for wildcard type name segments.
    fn init_validating_segment_regex() -> &'static Regex {
        VALIDATING_SEGMENT_REGEX.get_or_init(|| Regex::new(Self::VALIDATING_SEGMENT_PATTERN).unwrap())
    }
}

// Default to a single wildcard.
impl Default for WildcardTypeName {
    fn default() -> Self {
        Self {
            text: String::from("*"),
            regex: RegexBuilder::new(&convert_wildcard_to_regex("*"))
                .case_insensitive(true)
                .build()
                .unwrap()
        }
    }
}


// We implement `PartialEq` by hand for various types because WCTNs should be compared
// case insensitively. This obviates the need to `.to_string().to_lowercase()` for comparisons.
impl Eq for WildcardTypeName {}
impl PartialEq for WildcardTypeName {
    fn eq(&self, other: &Self) -> bool {
        self.text.to_lowercase() == other.text.to_lowercase()
    }
}

impl PartialEq<String> for WildcardTypeName {
    fn eq(&self, other: &String) -> bool {
        self.text.to_lowercase() == other.to_lowercase()
    }
}

impl PartialEq<str> for WildcardTypeName {
    fn eq(&self, other: &str) -> bool {
        self.text.to_lowercase() == other.to_lowercase()
    }
}

impl PartialEq<&str> for WildcardTypeName {
    fn eq(&self, other: &&str) -> bool {
        self.text.to_lowercase() == other.to_lowercase()
    }
}

// Enables using the construct `"Owner/Name".parse()` to convert a literal string into a WCTN.
impl FromStr for WildcardTypeName {
    type Err = WildcardTypeNameError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::parse(s)
    }
}

// Enables converting from a `String` and raising the appropriate error message for an invalid
// FQTN.
impl TryFrom<String> for WildcardTypeName {
    type Error = WildcardTypeNameError;
    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::parse(value.as_str())
    }
}

// Enables converting an FQTN into a string.
impl From<WildcardTypeName> for String {
    fn from(value: WildcardTypeName) -> Self {
        value.text
    }
}

impl From<WildcardTypeName> for Regex {
    fn from(value: WildcardTypeName) -> Self {
        value.regex
    }
}

// Enables using WCTNs in `format!()` and similar macros.
impl Display for WildcardTypeName {
    fn fmt(&self, f: &mut Formatter) -> std::fmt::Result {
        write!(f, "{}", self.text)
    }
}

// Enables passing a WCTN as `&str`
impl AsRef<str> for WildcardTypeName {
    fn as_ref(&self) -> &str {
        &self.text
    }
}

impl Hash for WildcardTypeName {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.text.to_lowercase().hash(state);
    }
}

impl TryFrom<FullyQualifiedTypeNameError> for WildcardTypeNameError {
    type Error = WildcardTypeNameError;
    fn try_from(value: FullyQualifiedTypeNameError) -> Result<Self, Self::Error> {
        match value {
            FullyQualifiedTypeNameError::InvalidOwnerSegment {
                segment_text
            } => Ok(WildcardTypeNameError::InvalidOwnerSegment { segment_text }),
            FullyQualifiedTypeNameError::InvalidNamespaceSegment {
                segment_text
            } => Ok(WildcardTypeNameError::InvalidNamespaceSegment { segment_text }),
            FullyQualifiedTypeNameError::EmptyNamespaceSegment {
                index
            } => Ok(WildcardTypeNameError::EmptyNamespaceSegment { index }),
            FullyQualifiedTypeNameError::InvalidNameSegment {
                segment_text
            } => Ok(WildcardTypeNameError::InvalidNameSegment { segment_text }),
            FullyQualifiedTypeNameError::EmptyOwnerSegment => Ok(WildcardTypeNameError::EmptyOwnerSegment),
            FullyQualifiedTypeNameError::MissingNameSegment => Ok(WildcardTypeNameError::MissingNameSegment),
            // No other errors should be converted
            _ => Err(WildcardTypeNameError::InvalidErrorConversion { err: value })
        }
    }
}