use schemars::{JsonSchema, json_schema};
use serde::{Deserialize, Serialize};

use crate::schemas::{dsc_repo::DscRepoSchema, schema_i18n};
use crate::settings::{DscSettingsResolvedField, DscSettingsScope};

mod fields;
pub use fields::*;

/// Defines the available settings for the tracing configuration in DSC.
/// 
/// This struct is used to represent the settings as they are defined in both [`DscPolicyFileData`]
/// and [`DscPreferenceFileData`].
/// 
/// [`DscPolicyFileData`]: crate::settings::DscPolicyFileData
/// [`DscPreferenceFileData`]: crate::settings::DscPreferenceFileData
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, DscRepoSchema)]
#[serde(rename_all = "camelCase")]
#[dsc_repo_schema(base_name = "tracing", folder_path = "settings/fields")]
pub struct TracingFileData {
    /// Specifies the trace level to use for logging and diagnostics.
    /// 
    /// This field controls the verbosity of the logs generated by DSC. Messages with a lower
    /// level than the specified trace level will be filtered out and not emitted.
    /// 
    /// The available trace levels, in order of increasing verbosity, are:
    /// 
    /// - `error`
    /// - `warn`
    /// - `info`
    /// - `debug`
    /// - `trace`
    pub level:  Option<TraceLevelField>,
    /// Specifies the trace format to use for logging and diagnostics.
    /// 
    /// This field controls the text that DSC emits to stderr for trace messages.
    /// 
    /// The available trace formats are:
    /// 
    /// - `default` - Colorized human-readable text with timestamps and log levels.
    /// - `plaintext` - Human-readable text without colorization.
    /// - `json` - Structured output as compressed JSON objects suitable for machine parsing.
    pub format: Option<TraceFormatField>,
}

impl JsonSchema for TracingFileData {
    fn schema_name() -> std::borrow::Cow<'static, str> {
        Self::default_schema_id_uri().into()
    }
    fn json_schema(_: &mut schemars::SchemaGenerator) -> schemars::Schema {
        json_schema!({
            "title": schema_i18n!("title"),
            "description": schema_i18n!("description"),
            "markdownDescription": schema_i18n!("markdownDescription"),
            "type": "object",
            "properties": {
                "level": {
                    "type": "string",
                    "enum": [
                        "error",
                        "warn",
                        "info",
                        "debug",
                        "trace"
                    ],
                    "title": schema_i18n!("level.title"),
                    "description": schema_i18n!("level.description"),
                    "markdownDescription": schema_i18n!("level.markdownDescription")
                },
                "format": {
                    "type": "string",
                    "enum": [
                        "default",
                        "plaintext",
                        "json"
                    ],
                    "title": schema_i18n!("format.title"),
                    "description": schema_i18n!("format.description"),
                    "markdownDescription": schema_i18n!("format.markdownDescription")
                }
            }
        })
    }
}

/// Defines the default values for the tracing configuration in DSC.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct TracingCodeDefaults {
    /// Indicates the default trace level to use for logging and diagnostics.
    pub level: TraceLevelField,
    /// Indicates the default trace format to use for logging and diagnostics.
    pub format: TraceFormatField,
}

/// Defines the default values for the tracing configuration in DSC.
/// 
/// The following snippet shows the effective code defaults as YAML data:
/// 
/// ```yaml
/// tracing:
///   level: warn
///   format: default
/// ```
pub const CODE_DEFAULT_TRACING: TracingCodeDefaults = TracingCodeDefaults {
    level: TraceLevelField::Warn,
    format: TraceFormatField::Default,
};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct TracingResolvedSettings {
    /// Indicates the minimum level of traces to emit.
    pub level: DscSettingsResolvedField<TraceLevelField>,
    /// Indicates the format to use when emitting traces.
    pub format: DscSettingsResolvedField<TraceFormatField>,
}

impl Default for TracingResolvedSettings {
    fn default() -> Self {
        let scope = DscSettingsScope::Default;
        Self {
            level: DscSettingsResolvedField::new(CODE_DEFAULT_TRACING.level, scope),
            format: DscSettingsResolvedField::new(CODE_DEFAULT_TRACING.format, scope),
        }
    }
}
